#include "./_data_nvm/data_nvm_5219_Vc_Dec09_13.h"	

		const unsigned int ADDR_SET_CALIBRATE 			= (0*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_CAPACITY_CALI 			= (1*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 2 uint16_t */
		const unsigned int ADDR_POINT_ZERO 				= (3*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 2 uint16_t */
		const unsigned int ADDR_FACTOR_CALIBRATE 	= (5*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 2 uint16_t */
		const unsigned int ADDR_LENGUAGE 					= (7*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t	*/
		//const unsigned int ADDR_UNITS 					= (8*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_CAPACITY 					= (9*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_PORC_REF 					= (10*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_DIVISION_MINIMA		= (11*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_DECIMAL_TOTAL 		= (12*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_REDONDEO_TOTAL 		= (13*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_REDONDEO_VENTA 		= (14*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_DECIMAL_PRECIO 		= (15*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_ZERO_TRACKING 		= (16*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_FORMATO_IMPRESION	= (17*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_MSG_UNLOAD 				= (18*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_TIME_OFF 					= (19*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_COUNTER_CALIBRATION 		= (20*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_COUNTER_CONFIGURATION 	= (21*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		//const unsigned int ADDR_VENTA_TOTAL 				= (22*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 2 uint16_t */
		const unsigned int ADDR_MULTIRRANGO_OFF		= (24*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 2 uint16_t */
		const unsigned int ADDR_MODELO						= (26*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_TYPEBEEPER				= (27*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_BACKLIGHT				= (28*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_BAUD_RATE 				= (29*2 + ADDRESS_SCALE_CONFIG_PAGE);	/* 1 uint16_t */
		const unsigned int ADDR_MSGBAT						= (30*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_DEBUG							= (31*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_FACTOR_M					= (32*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 2 uint16_t */
		const unsigned int ADDR_MODE_INC_DIV			= (34*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_COUNT_RANGE				= (35*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_CARACTER_CONTROL	= (36*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_NEW_LINE_PRINTER	= (37*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_MONEDA						= (38*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		//const unsigned int ADDR_COUNT_OVERLOAD			= 39; /* 1 uint16_t */
		//const unsigned int ADDR_VALUE_OVERLOAD			= 40; /* 2 uint16_t */
		const unsigned int ADDR_VOLT_BATT					= (42*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 2 uint16_t */
		const unsigned int ADDR_VOLT_ADAP					= (44*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 2 uint16_t */
		//const unsigned int ADDR_TEST_TECLADO				= 46*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_DECIMAL_WEIGHT		= (47*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_TEMPERATURE 			= (48*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 2 uint16_t */
		const unsigned int ADDR_USB_ENABLE 				= (50*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_BLE_ENABLE 				= (51*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_SELECT_HS 				= (52*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_HARDFAULT 				= (53*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_HF_Multir					= (54*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_HF_ZERO 					= (55*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 2 uint16_t */
		const unsigned int ADDR_UPDATEFIRM				= (57*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_MSGADAPT					= (58*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_PWM_FACTOR				= (59*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_TRIMULTIRANGO			= (60*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_TRIMULTIRANGO_STATE  = (61*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_PROTEK            = (62*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */  
		const unsigned int ADDR_CAPACIDAD         = (63*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_DECIMAL_WEIGHT_LB   = (64*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_CAPACITY_LB				  = (65*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */
		const unsigned int ADDR_DIVISION_MINIMA_LB	= (66*2 + ADDRESS_SCALE_CONFIG_PAGE); /* 1 uint16_t */

		//VALORES GUARDADOS EN LA PAGINA DE TEST DE CALIDAD Y USUARIO
		const unsigned int ADDR_VENTA_TOTAL 				= 0 + ADDRESS_QLTY_AND_CNTRS_PAGE;	/* 2 uint16_t */
		const unsigned int ADDR_TEST_TECLADO				= 4 + ADDRESS_QLTY_AND_CNTRS_PAGE; /* 1 uint16_t */
		const unsigned int ADDR_COUNT_OVERLOAD			= 6 + ADDRESS_QLTY_AND_CNTRS_PAGE; /* 1 uint16_t */
		const unsigned int ADDR_VALUE_OVERLOAD			= 8 + ADDRESS_QLTY_AND_CNTRS_PAGE; /* 2 uint16_t */
		const unsigned int ADDR_LIMITE_STABLE 			= 12 + ADDRESS_QLTY_AND_CNTRS_PAGE;  /* 1 uint16_t */
		const unsigned int ADDR_UNITS 							= 14 + ADDRESS_QLTY_AND_CNTRS_PAGE;  /* 1 uint16_t */
		const unsigned int ADDR_KG_LB  							= 16 + ADDRESS_QLTY_AND_CNTRS_PAGE;		

#endif
